export const nox = {
  name: "Nox Sétanta",
  descriptor: "Meticulous Eldritch",
  type: "Witch",
  focus: "Who Inks Spells on Skin",
  tier: 1,
  effort: 1,
  xp: {
    game: 0,
    chance: 15
  },
  armor: 1,
  advancement: {
    pool: false,
    edge: false,
    effort: false,
    skill: false,
    other: false,
  },
  stats: {
    might: {
      name: "might",
      pool: 9,
      edge: 0,
      defense: 'p',
      current: 10,
    },
    speed: {
      name: "speed",
      pool: 11,
      edge: 0,
      defense: 'p',
      current: 10,
    },
    intellect: {
      name: "intellect",
      pool: 18,
      edge: 1,
      defense: 't',
      current: 10,
    },
  },
  recoveryAdd: 0,
  recoveryRoll: {
    action: false,
    tenMin: false,
    oneHr: false,
    tenHr: false,
  },
  damageTrack: {
    hale: true,
    impared: false,
    debilitated: false,
    dead: false,
  },
  skills: [
    {
      name: "Light Weapons",
      description: "You can use light weapons without penalty.",
      source: 'CSRD',
      stat: '',
      training: 'p',
    },
    {
      name: "Medium, heavy weapons",
      description: "You have an inability with medium weapons and heavy weapons; your attacks with medium and heavy weapons are hindered.",
      source: 'CSRD',
      stat: '',
      training: 'i',
    },
    {
      name: "Ward",
      description: "You have a shield of energy around you at all times that helps deflect attacks. You gain +1 to Armor. Enabler.",
      source: 'CSC, 196',
      stat: 'i',
      training: 'p',
    },
    {
      name: "Detail Oriented",
      description: "You have an eye for detail. You are trained in any task that involves finding or noticing small details. ",
      source: 'In Translation, 20',
      stat: 'i',
      training: 't',
    },
    {
      name: "Dexterous",
      description: "Being careful includes improved fine motor control. You are trained in any task that involves manipulating small or delicate objects, working with machinery, or doing similar tasks where a shaking hand could be the difference between success and failure",
      source: 'In Translation, 20',
      stat: 'i',
      training: 't',
    },
    {
      name: "Shield",
      description: "You’re hard to fool because your cognizance is more than a tool—it’s a shield. You’re trained in Intellect defense tasks. ",
      source: 'In Translation, 20',
      stat: 'i',
      training: 't',
    },
    {
      name: "Perfectionist",
      description: "Your conscientious eye for detail sometimes puts off strangers. Any task involving positive social interaction is hindered.",
      source: 'In Translation, 20',
      stat: 'i',
      training: 'i',
    },
    {
      name: "Eldritch",
      description: "Trained in all tasks understanding and identifying the supernatural.",
      source: 'Eldritch',
      stat: 'i',
      training: 't',
    },
    {
      name: "Magic Burst",
      description: "At the start of every session roll 1d20 and make note of it. Anytime you cast a spell and the roll matches this number a magical effect is triggered regardless of whether or not you succeeded or failed the roll. (5% chance of happening) At the beginning of every session you may choose to roll a second number increasing the chances of a magical effect triggering and also increases your subtle cypher limit by 1 for the session.",
      source: 'Eldritch',
      stat: 'i',
      training: 'p',
    },
    {
      name: "Magical Repertoire",
      description: "The number of subtle cyphers you can bear at the same time increases by two. If you spend one hour preparing your magic, you can fill any of your open cypher slots with subtle cyphers chosen randomly by the GM (this hour can be part of a one-hour or ten-hour recovery action if you are awake for the entire time). As part of this preparation process, you may discard any number of subtle cyphers you carry to make room for more subtle cyphers. Enabler.",
      source: 'GF, 32',
      stat: 'i',
      training: 'p',
    },
    {
      name: "Cypher Casting",
      description: "You can cast any of your subtle cyphers on another creature instead of yourself. You must touch the creature to affect it. Enabler",
      source: 'GF, 29',
      stat: 'i',
      training: 'p',
    },
    {
      name: "Hobbies",
      description: "Trained in drawing and cooking",
      source: 'Background',
      stat: 'i',
      training: 'p',
    },
  ],
  abilities: [

    {
      name: "Onslaught",
      description: "You attack a foe using energies that assail either their physical form or their mind. In either case, you must be able to see your target. If the attack is physical, you emit a short-range ray of force that inflicts 4 points of damage. If the attack is mental, you focus your mental energy to blast the thought processes of another creature within short range. This mindslice inflicts 2 points of Intellect damage (ignores Armor). Some creatures without minds (such as robots) might be immune to your mindslice. Action.",
      source: 'CSC, 167',
      cost: '1',
      stat: 'i',
      training: 'p',
    },
    {
      name: "Far Step",
      description: "You have a shield of energy around you at all times that helps deflect attacks. You gain +1 to Armor. Enabler.",
      source: 'CSC, 138',
      cost: '2',
      stat: 'i',
      training: 'p',
    },
    {
      name: "Hedge Magic",
      description: "You can perform small tricks: temporarily change the color or basic appearance of a small object, cause small objects to float through the air, clean a small area, mend a broken object, prepare (but not create) food, and so on. You can’t use Hedge Magic to harm another creature or object. Action.",
      source: 'CSC, 149',
      cost: '1',
      stat: 'i',
      training: 'p',
    },
  ],
  attacks: [
    {
      name: 'unarmed',
      cost: 0,
      stat: 'm',
      damage: {
        value: 2,
        type: 'b'
      },
      training: 'p',
      eased: true,
    },
    {
      name: 'Onslaught - physical',
      cost: 1,
      stat: 'i',
      damage: {
        value: 4,
        type: 'm'
      },
      training: 'p',
      eased: false,
    },
    {
      name: 'Onslaught - mindslice (ignores armor)',
      cost: 1,
      stat: 'i',
      damage: {
        value: 2,
        type: 'm'
      },
      training: 'p',
      eased: false,
    }
  ],
  cypherLimit: {
    base: 3,
    add: 2,
  },
  cyphers: [],
  equipment: [ {
    name: 'Appropriate Clothes',
    description: '',
    source: '-',
    level: 3,
    cost: 'm',
  },
  {
    name: 'Computer',
    description: '',
    source: '-',
    level: 3,
    cost: 'e',
  },
  {
    name: 'Smart Phone',
    description: '',
    source: '-',
    level: 3,
    cost: 'e',
  },
  {
    name: 'Tattoo Inking Set',
    description: '',
    source: '-',
    level: 3,
    cost: 'e',
  },
],
money: {
  i: 4,
  m: 2,
  e: 0,
  v: 0,
  o: 0,
}
}
