export const nox = {
  name: "Nox Sétanta",
  descriptor: "Meticulous Eldritch",
  type: "Witch",
  focus: "Who Inks Spells on Skin",
  tier: 1,
  effort: 1,
  xp: {
    game: 0,
  },
  advancement: {
    pool: false,
    edge: false,
    effort: false,
    skill: false,
    other: false,
  },
  stats: {
    might: {
      name: "might",
      pool: 10,
      edge: 0,
      defense: 'p',
      current: 10,
    },
    speed: {
      name: "speed",
      pool: 10,
      edge: 0,
      defense: 'p',
      current: 10,
    },
    intellect: {
      name: "intellect",
      pool: 10,
      edge: 0,
      defense: 'p',
      current: 10,
    },
  },
  recoveryAdd: 0,
  recoveryRoll: {
    action: false,
    tenMin: false,
    oneHr: false,
    tenHr: false,
  },
  damageTrack: {
    hale: true,
    impared: false,
    debilitated: false,
    dead: false,
  },
  skills: [],
  abilities: [],
  attacks: [],
  cypherLimit: {
    base: 2,
    add: 0,
  },
  cyphers: [],
  equipment: [],
  armor: [],
}
